[package]
name = "arrow-json"
version = "0.1.0"
authors = ["Adheip Singh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "3.0.0"
